### ISSUE TITLE
Gradle remote script unavailable

### ISSUE THREAD

**Issue by SzczygielDev** [przelewy24/p24-mobile-lib-flutter#17] opened 2024-03-29 11:31 UTC
Remote script url defined in build.gradle refuses connection and it cause app build to fail.

```
What went wrong:
A problem occurred evaluating project ':p24_sdk'.
> Could not get resource 'https://mobile.przelewy24.pl/p24lib.gradle'.
   > Could not HEAD 'https://mobile.przelewy24.pl/p24lib.gradle'.
      > Connect to mobile.przelewy24.pl:443 [mobile.przelewy24.pl/IP] failed: Connection refused: connect
```

https://github.com/przelewy24/p24-mobile-lib-flutter/blob/bd098ac6e10d8996deb60dc9c5683517805d2821/android/build.gradle#L3

**Comment by pajuja92** [comment] 2024-03-29 12:08
The same issue occurred in my flutter project

```
* Where:
Build file '/Users/{user}/.pub-cache/hosted/pub.dev/p24_sdk-1.0.54/android/build.gradle' line: 3

* What went wrong:
A problem occurred evaluating project ':p24_sdk'.
> Could not get resource 'https://mobile.przelewy24.pl/p24lib.gradle'.
   > Could not HEAD 'https://mobile.przelewy24.pl/p24lib.gradle'.
      > Connect to mobile.przelewy24.pl:443 [mobile.przelewy24.pl/91.216.191.100] failed: Connection refused
```

**Comment by mareklat** [comment] 2024-03-29 12:20
This is our network problem. We're working on it. I'll let you know when it's fixed

**Comment by pajuja92** [comment] 2024-04-02 06:26
Hi, what is the issue status?

**Comment by bbenetskyy** [comment] 2024-04-02 06:40
This is blocking us from the production build. Is there any working workaround?

**Comment by PawelSzymanski89** [comment] 2024-04-02 07:16
Any up?

**Comment by mareklat** [comment] 2024-04-02 08:06
We found the cause of the problem, it will be fixed by the end of the day

**Comment by mareklat** [comment] 2024-04-02 11:31
The network problem has been fixed and the file should now be available

**Closed by mareklat** 2024-04-02 11:31 UTC

**Comment by pajuja92** [comment] 2024-04-02 11:37
Thanks!
